name: Publish test library version on Github packages
on:
  pull_request:
    types: [opened]
jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - name: Set the value
        id: step_one
        run: |
            echo "PACKAGE_VERSION=$(npm show . version)" >> $GITHUB_ENV
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'
      - run: 
      - run: npm ci
      - run: git config --global user.name "GitHub CD bot"
      - run: git config --global user.email "pkaczmarek@cleeng.com"
      - run: npm version ${{ env.PACKAGE_VERSION}}-${{ github.event.number }}-${{ github.event.pull_request.head.sha }}
      - run: npm run compile