name: Prepare feature package
on:
  pull_request:
    types: [opened, synchronize, edited]
jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          registry-url: 'https://npm.pkg.github.com'
          always-auth: true
          # scope: '@cleeng'
      - run: |
            echo "@cleeng:registry=https://npm.pkg.github.com" >> ${{ github.workspace }}/.npmrc
      - run: npm ci
      - run: |
            echo "PACKAGE_VERSION=$(npm show . version)" >> $GITHUB_ENV
      - run: git config --global user.name "GitHub CD bot"
      - run: git config --global user.email "pkaczmarek@cleeng.com"
      - run: npm version ${{ env.PACKAGE_VERSION}}-${{ github.event.number }}-${{ github.event.pull_request.head.sha }}
      - run: npm run compile
      - run: npm config get registry
      - run: npm publish  --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}